export const dummyInstrumentData = [
    {
      "instrumentId": 1,
      "instrumentName": "Armstrong - Jacobi",
      "instrumentType": "Private Equity",
      "sector": "Consumer Staples",
      "country": "US",
      "instrumentCurrency": "USD",
      "isTradeable": false,
      "createdAt": "2019-02-01 00:00:00",
      "modifiedAt": "2019-02-01 00:00:00",
      "notes": "Private Equity; Consumer Staples; Tradable Instrument"
    },
    {
      "instrumentId": 2,
      "instrumentName": "Armstrong - Reichert",
      "instrumentType": "Private Equity",
      "sector": "Information Technology",
      "country": "US",
      "instrumentCurrency": "USD",
      "isTradeable": true,
      "createdAt": "2019-02-01 00:00:00",
      "modifiedAt": "2019-02-01 00:00:00",
      "notes": "Private Equity; Information Technology; Tradable Instrument"
    },
    {
      "instrumentId": 3,
      "instrumentName": "Armstrong Sporer and Nikolaus",
      "instrumentType": "Private Equity",
      "sector": "Healthcare",
      "country": "US",
      "instrumentCurrency": "USD",
      "isTradeable": true,
      "createdAt": "2019-02-01 00:00:00",
      "modifiedAt": "2019-02-01 00:00:00",
      "notes": "Private Equity; Healthcare; Tradable Instrument"
    },
    {
      "instrumentId": 4,
      "instrumentName": "Auer - Bailey",
      "instrumentType": "Private Equity",
      "sector": "Industrials",
      "country": "US",
      "instrumentCurrency": "USD",
      "isTradeable": true,
      "createdAt": "2019-02-01 00:00:00",
      "modifiedAt": "2019-02-01 00:00:00",
      "notes": "Private Equity; Industrials; Tradable Instrument"
    },
    {
      "instrumentId": 5,
      "instrumentName": "Bailey - Rosenbaum",
      "instrumentType": "Private Equity",
      "sector": "Information Technology",
      "country": "US",
      "instrumentCurrency": "USD",
      "isTradeable": true,
      "createdAt": "2019-02-01 00:00:00",
      "modifiedAt": "2019-02-01 00:00:00",
      "notes": "Private Equity; Information Technology; Tradable Instrument"
    },
    {
      "instrumentId": 6,
      "instrumentName": "Bartoletti Group",
      "instrumentType": "Private Equity",
      "sector": "Industrials",
      "country": "US",
      "instrumentCurrency": "USD",
      "isTradeable": true,
      "createdAt": "2019-02-01 00:00:00",
      "modifiedAt": "2019-02-01 00:00:00",
      "notes": "Private Equity; Industrials; Tradable Instrument"
    },
    {
      "instrumentId": 7,
      "instrumentName": "Barton - Stark",
      "instrumentType": "Private Equity",
      "sector": "Information Technology",
      "country": "US",
      "instrumentCurrency": "USD",
      "isTradeable": true,
      "createdAt": "2019-02-01 00:00:00",
      "modifiedAt": "2019-02-01 00:00:00",
      "notes": "Private Equity; Information Technology; Tradable Instrument"
    },
    {
      "instrumentId": 8,
      "instrumentName": "Batz - Reichert",
      "instrumentType": "Private Equity",
      "sector": "Information Technology",
      "country": "US",
      "instrumentCurrency": "USD",
      "isTradeable": true,
      "createdAt": "2019-02-01 00:00:00",
      "modifiedAt": "2019-02-01 00:00:00",
      "notes": "Private Equity; Information Technology; Tradable Instrument"
    },
    {
      "instrumentId": 9,
      "instrumentName": "Batz - Ziemann",
      "instrumentType": "Private Equity",
      "sector": "Information Technology",
      "country": "US",
      "instrumentCurrency": "USD",
      "isTradeable": true,
      "createdAt": "2019-02-01 00:00:00",
      "modifiedAt": "2019-02-01 00:00:00",
      "notes": "Private Equity; Information Technology; Tradable Instrument"
    }];